### ISSUE TITLE
Closures do not generate type definitions

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#299]
When we compile `fn`s, sometimes it might be necessary to emit type definitions. For instance here (taken from my physics library):

```clojure
(defmodule Example
  (defn parallel [resistances]
    (Array.reduce (fn [x y] (+ @x (/ 1.0 @y))) 0.0 resistances))
)
```

If we compile this as-is, we generate invalid C, because `Array__double` is not emitted. I didn’t use an example function using this with a literal here, because the literal itself would trigger the typedef, causing the error to disappear.

Cheers

**Comment by eriksvedang** [comment]
Oh, this old bug rears its ugly head again! Should be an easy fix...

**Comment by eriksvedang** [comment]
This turned out to be a problem even for non-lambdas in this case, so it's very strange that we haven't caught it before. Now it should be fixed at least..!

**Comment by hellerve** [comment]
This is not fixed yet. If I put the code above into a file, it will still generate invalid C.

**Comment by hellerve** [comment]
Nevermind. Pulling helps (oops) 😸
