### ISSUE TITLE
Identifiers starting with digits should throw a parse error

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#414]
At present the Carp REPL will allow for definitions using digits as identifiers like the following:

```clojure
(deftype Flag [4 Int])
(def 4 4)
(defn 4 [x] x)
```

Declarations like the above are more often than not likely erroneous and unintentional. Each of the above declarations results in different behaviors. `(deftype Flag [4 Int])` generates invalid C identifiers and fails to compile, `(def 4 4)` seems to generate a parenthesis parsing error and causes the repl to exit/fail on (build). `(defn 4 [x] x)` defines a function that's not callable (so far as I can discern) but compiles just fine.

For simplification, and to help programmers avoid unwitting errors in declarations, Carp should throw a parse error when a digit is used as the first character of an identifier.  

@hellerve

**Comment by hellerve** [comment]
This is super fun and weird. Apparently the compiler pushes the entire expression through to the code emitter as is, because it generates code like `int (def 4 4);` and `(def 4 4) = 4;`. Note how it actually knows that this is an integer variable that gets 4 assigned to it, but it still uses the entire expression as name.

NB if you want to work on this: we’ll have to hunt for the place where this happens, and I’d probably go from the code emitter backwards and add an error case somewhere in the `Eval` module in the end. If you’re stumped, or don’t know where to begin, you can always contact me!

**Comment by eriksvedang** [comment]
Wow, I can't believe this has lived on for this long..! If any of you don't want to fix this I'll do it eventually.

**Comment by scolsen** [comment]
Happy to take a shot at this. @hellerve, thanks for the tips! I'll let you know if I have any questions/run into difficulties.

**Comment by scolsen** [comment]
Alrighty, I started up a draft PR #419 to get working on this! @hellerve @eriksvedang.

Started out with just defn for now, I'll be following up with def and deftype soon. Turns out integers are correctly parsed as `Num XObjs` in the `def<x>` declarations, so we just have to add checks on the identifiers in Eval. For now I took a general route and check that identifiers are `Sym XObjs`. If we want we can take a narrow approach instead and check against Nums specifically. 

I poked around Emit.hs a bit as well and found the defn functions that require changing. I believe we'll need to modify those too, but I haven't confirmed yet. For now, the REPL at least errors on `(defn 4 [] 4)`

Let me know if you think I'm throwing the error in the wrong place! I took some time to pore over the code, but I am certainly no expert on it, so I appreciate any checks you can provide on my understanding!

**Comment by eriksvedang** [comment]
Oh, I merged what you'd done so far (not used to drafts, though that seems like a handy feature).

I think checking for Sym is the right approach. So far I think you've understood where to put things very well! :)

**Comment by eriksvedang** [comment]
Should I close this now?

**Comment by hellerve** [comment]
`let` still isn’t fixed, e.g. `(defn main [] (let [4 4] (IO.println "hi")))`. Once that is done, I think we can  close it!

**Comment by eriksvedang** [comment]
Right!

**Comment by scolsen** [comment]
Sorry for the delay! 

I've started #447 to resolve the let issue. Top level lets are taken care of. However, it looks like inner lets `(defn main [] (let [4 4] true))` are not passed through `eval` at this point, and instead are passed to qualify directly. 

I'm having a bit more trouble understanding where to account for this case. I've attempted modifying Qualify.hs 's  handling of lets, but it results in a bunch of unexpected failed definitions in `Int`

Any thoughts?

**Comment by scolsen** [comment]
Are there any other outliers we should take care of here?

Thus far I think the following forms are accounted for:

* deftype
* def
* defn
* let

Is it possible this is an error for `fn` and isn't handled yet as well? (can't check atm, but will tomorrow if no one else gets the chance)

**Comment by hellerve** [comment]
`fn` is in fact also affected. I’ll add a fix for that as well.

**Comment by eriksvedang** [comment]
@hellerve Do you have time to finish this or should I do it?

**Comment by hellerve** [comment]
Not before the weekend, probably :(
