### ISSUE TITLE
`hidden` in submodule confuses the compiler

### ISSUE THREAD

**Issue by TimDeve** [carp-lang/Carp#792]
The following code:
```clojure
(defmodule Modone
 (defmodule Modtwo
  (hidden funone)
  (defn funone [] @"Hello")
  (defn funtwo [] (funone))))

(use Modone.Modtwo)

(defn main []
 (println* (the String (funtwo))))
```
Produces this error:
```
I encountered an error when emitting code:

I found an ambiguous symbol `funone` at line 5, column 20 in '/mnt/c/Users/tim/dev/sandbox/carpsudmod/main.carp'

Possibilities:
  Modone.Modtwo.funone
  Modone.funone

All possibilities have the correct type.

Traceback:
(build) at Compiler (Build & Run):1:5.
```

It only happens if the function is labeled with `hidden`.

Edit: Same with `private` and `sig` so probably related to `meta`

**Comment by eriksvedang** [comment]
I think this is solved now?

**Comment by TimDeve** [comment]
Not on latest master for me.

**Comment by scolsen** [comment]
It's still an issue--it's proving a little tricky to solve. For some reason, the `MetaSet` primitive doesn't get the full stack context-- it only gets the top level module:

> Somehow pathstrings for submodules aren't captured in the pathstrings that primitiveMetaSet recieves
so when it's called before a form exists it only adds a DocStub to the top-level module

```
鲤 :i Sub
Sub : Module = {
    Mod : Module = {
        Ule : Module = {
            a-func : (Fn [a] a)
            hey : (Fn [(Ref String a)] String)
        }
    }
    a-func : a
}
```

> I tried altering primitiveDefModule...but it pretty muich breaks everything
what's odd is that the module itself/defining binding is correct
only MetaSet doesn't get the full story for some reason

> So, I think the issue underlying #823 is that we pop off a module name everytime we define a brand new module:

```
鲤 (load "tricky.carp")
pathstrings:["Sub","Mod","Ule"]
pathstrings:["Sub","Mod"]
pathstrings:["Sub"]
鲤
```

> On the face of it, this isn't problematic in eval because we dive down to eval the other expressions, but when it comes to meta-set of a sig it's receiving only the last path string, with the interior modules popped off, which assigns the sig to the wrong module.

For some reason, when metaset  forward declarations are evaluated it only gets `[Sub]` as its context paths, even though the paths should be `[Sub, Mod, Ule]` -- weirdly this issue only happens for metaSet

**Comment by TimDeve** [comment]
I guess I raised this issue twice 😅 sorry.
Maybe this one could be closed in favour of https://github.com/carp-lang/Carp/issues/823

**Comment by scolsen** [comment]
Hah! even worse....I didn't even realize that the link was a different issue # 🤦‍♂️

**Comment by eriksvedang** [comment]
Did this get fixed?

**Comment by TimDeve** [comment]
Not sure, I've stopped using submodules because there was too many gotchas.

**Comment by scolsen** [comment]
I *think*, but I'm not certain, that these issues probably stem from the way we currently handle internal environments, which I find somewhat confusing--there are a lot of places in the compiler where the depth of environments and current environment we're looking at is implicit. I think there are also a couple of places where we are using non-recursive lookups where we should be using recursive lookups and vice versa.

**Comment by scolsen** [comment]
fixed in #1078
