### ISSUE TITLE
Setting meta on interfaces in modules fails

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#842]
As discovered in #833, setting `meta` on `definterface` implementations in modules currently makes the compiler hang. @scolsen seems to have a hunch where this is coming from (for reference, [here is his comment](https://github.com/carp-lang/Carp/pull/833#discussion_r429683191)).

Cheers

**Comment by eriksvedang** [comment]
Perhaps this is solved now with the improvements to meta data?

**Comment by hellerve** [comment]
This does seem to work now!

**Comment by hellerve** [comment]
Ah, no, the problem is not with interfaces, but their implementation, and it still persists.

**Comment by eriksvedang** [comment]
Thanks for checking!

**Comment by scolsen** [comment]
> Ah, no, the problem is not with interfaces, but their implementation, and it still persists.

**Comment by scolsen** [comment]
I just tried this out and it seems to be fixed now?

```clojure
(defmodule Foo (doc zero "fbk") (implements zero zero) (defn zero [] 1))
:i zero

Implementing: (zero)
Foo.zero : (Fn [] Int)
Defined at line 1, column 56 in 'REPL'
Documentation: fbk
```

**Comment by hellerve** [comment]
@scolsen There is commented out code in `Tuples.carp` that documents the `zero` interface there that seems to hang the compiler.

**Comment by hellerve** [comment]
This is the affected section:

https://github.com/carp-lang/Carp/blob/c1e794c4ccf33b965bd32b6713014b72d3d7fe3c/core/Tuples.carp#L70-L73

**Comment by scolsen** [comment]
Thanks! Oddly enough, this seems to work for me at the moment in the REPL and for extremely simple cases, so I'm still trying to determine precisely where the problem occurs

**Comment by scolsen** [comment]
So, for some reason, when we try to eval that particular doc string this is where the code hangs:

```
ta setting: awith context: Random.a
meta setting: awith context: Random.a
meta setting: cwith context: Random.c
meta setting: cwith context: Random.c
meta setting: mwith context: Random.m
meta setting: mwith context: Random.m
meta setting: swith context: Random.s
meta setting: swith context: Random.s
meta setting: seedwith context: Random.seed
meta setting: seed-fromwith context: Random.seed-from
meta setting: randomwith context: Random.random
meta setting: _with context: Random._
meta setting: _with context: Random._
meta setting: _with context: Random._
meta setting: dflt-lenwith context: Map.dflt-len
meta setting: createwith context: Map.create
meta setting: create-with-lenwith context: Map.create-with-len
meta setting: putwith context: Map.put
meta setting: put!with context: Map.put!
meta setting: get-with-defaultwith context: Map.get-with-default
meta setting: getwith context: Map.get
```

**Comment by scolsen** [comment]
which is quite strange since it's not even in the module or function we're adding a docstring to!

**Comment by scolsen** [comment]
Changing the load order of `Map.carp` also eliminates the hang .... 😮

**Comment by scolsen** [comment]
Quite bizarre

**Comment by scolsen** [comment]
So, I think the problem ultimately stems from generating the modules via a macro, normally when we doc a zero def, we get:

```
meta setting: zerowith context: String.zero
```

But it seems the macro emitted calls instead produce:

```
meta setting: reversewith context: reverse
meta setting: zerowith context: zero
```

**Comment by scolsen** [comment]
Which winds up replacing the interface binder, leading to a hang--at least I think that's what's happening

**Comment by scolsen** [comment]
I'm not sure that there's anyway we can check that a macro expansion is defining a module and set the context appropriately--instead we may just have to support forward meta sets on qualified syms...but that's also problematic

**Comment by scolsen** [comment]
So, I think ultimately the problem stems from the fact that our implementation of `doc`, which forces an `eval` just like all the other meta-set! macros:

```
(eval (list 'meta-set! name "doc" (Dynamic.String.concat (list-to-array-internal separated [])))))) 
```

so, when the defmodule for a generated module is expanded, the call to `doc` is *also immediately expanded and evaled under the incorrect environment*:

```
macro expanding: (defmodule Triple (doc init-from-refs "initializes a `Triple` from member references.") (defn init-from-refs [a-val b-val c-val] (init (copy a-val) (copy b-val) (copy c-val))) (defn = [t1 t2] (and* (= (a (ref t1)) (a (ref t2))) (= (b (ref t1)) (b (ref t2))) (= (c (ref t1)) (c (ref t2))))) (implements = Triple.=) (defn < [t1 t2] (TripleRef.< (ref t1) (ref t2))) (implements < Triple.<) (defn > [t1 t2] (TripleRef.> (ref t1) (ref t2))) (implements > Triple.>) (doc reverse "reverses a `Triple` by reversing its member positions.") (defn reverse [t] (init (copy (c t)) (copy (b t)) (copy (a t)))) (defn zero [] (init (zero) (zero) (zero))))
macro expanding: Triple
macro expanding: (doc init-from-refs "initializes a `Triple` from member references.")
macro expanding: (meta-set! init-from-refs "doc" "initializes a `Triple` from member references.\n")
macro expanding: init-from-refs
macro expanding: "doc"
macro expanding: "initializes a `Triple` from member references.\n"
```

What causes the hang in this case is that `zero` is re-written at the global level. So there are actually two problems here:

1. We are immediately evaluating the call to `doc` when what we really want is a call to it *later*.
2. Somehow such global rewrites *invalidate* existing interfaces in such a way that it causes a hang.

2. is the more serious issue. As for 1. we'll likely want a variant of each `meta-set` macro that doesn't force an `eval`.

@hellerve FYI

**Comment by scolsen** [comment]
I've confirmed that removing the `eval` from the `doc` macro not only results in the desired behavior but also retains existing behavior on other doc calls--so we likely want to remove the evals from every one of these macros.

**Comment by eriksvedang** [comment]
Ok that’s good news! Ideally we don’t need these inner evals at all, do you think that’s possible?

**Comment by eriksvedang** [comment]
I have an idea also that could help debug this – some kind of validation function that walks the environment and asserts that their path matches their location in the module tree.

**Comment by scolsen** [comment]
That sounds useful! I think the second issue (the interface being overwritten) happens because we *don't* look in the type env (where interfaces live) when resolving `meta-set`--so, the incorrect doc call winds up producing a `zero` in the global environment that *doesn't* implement `zero` (the interface) and so the compiler gets confused somewhere and is unable to resolve certain subsequent calls to `zero` (that have a conflicting generic type sig) since it can't differentiate between the newly created DocStub `zero` in global env and the `zero` interface in the type env

and the lookup loops

**Comment by scolsen** [comment]
Probably when no impl for an interface is found we should fallback to looking for a global definition of the same name

**Comment by scolsen** [comment]
Adding a check for the type env in doc calls eliminates the hang  and catches the mistake :)

```
[WARNING] Definition at line 19, column 3 in '/Users/scottolsen/dev/Carp/core/Unit.carp' changed type of 'Unit.zero' from Interface to (Fn [] ())
```

It doesn't catch the mistake until the last implementation of the original interface...but it's better than hanging I suppose.

**Comment by eriksvedang** [comment]
OK, that check sounds like a great first defense.

Perhaps we could have some anti-infinite-loop code in the lookup function, basically making sure that you're always digging deeper..? Haven't thought about it much, but infinite loops is never fun so we should probably take some drastic measures to rule them out. 

Side note: Kind of ironically, infinite loops happen more often in Haskell than in any other language I use – probably due to pattern matching and tail recursion (and the lack of totality checker like they have in Idris, of course).

**Comment by jacereda** [comment]
I would start compiling with `-Wall`, it should detect some situations that could lead to infinite loops. I can give it a try.

**Comment by eriksvedang** [comment]
> I would start compiling with -Wall, it should detect some situations that could lead to infinite loops. I can give it a try.

Yes, that is a great idea!
